### ISSUE TITLE
No module named 'scikits'

### ISSUE THREAD

**Issue by xenhua** [bmcage/odes#103]
I have successfully installed scikits.odes using the following commands: 

```
cmake -DLAPACK_ENABLE=ON -DCMAKE_INSTALL_PREFIX=/usr/local/lib/sundials-3.1.1/ -DEXAMPLES_INSTALL_PATH=/home/xenhua/Downloads/cantera-related/sundials-3.1.1/examples-3.1.1 ../sundials-3.1.1/
make
sudo make install
```
`export SUNDIALS_INST=/usr/local/lib/sundials-3.1.1/`

`pip3 install scikits.odes`

I can then verify the correct installation by using the "pip3 freeze" command: For example, 

```
pip3 freeze | grep scikits
scikits.bootstrap==0.3.3
scikits.odes==2.4.0
```

and

```
pip freeze | grep scikit
scikit-learn==0.21.2

```
But then when I try to run  the tests by importing scikits.odes as od, I get the following "ModuleNotFoundError:

```
import scikits.odes as od
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'scikits'


```

**Comment by bmcage** [comment]
can you provide the output of pip3 install? 

Any reason you did not provide the flag  `-DSUNDIALS_INDEX_TYPE=int32_t` to sundials?
See #95 for a likewise bug report and pip3 output. Above flag was needed.

**Comment by bmcage** [comment]
No feedback received, closing
