### ISSUE TITLE
<sundials/sundials_pcg.h> not found

### ISSUE THREAD

**Issue by cuihantao** [bmcage/odes#109]
Hi,

Thanks for bringing together this very nice work! I tried to compile it on macOS Catalina with Sundials 5.0.0. It says #include <sundials/sundials_pcg.h> file not found. 

I downgraded to sundials=4.1.0 and it compiles. There is no particular reason for me to use a higher version though. I'm posting the issue here for reference. 

I will look into it later.

**Comment by ingegno** [comment]
5.0.0 is not supported yet. There is a development branch where this error is already corrected, though the branch does not compile yet, see https://github.com/bmcage/odes/tree/sundials_5_0

**Comment by cuihantao** [comment]
Thanks!
