### ISSUE TITLE
CVODE default multistep method?

### ISSUE THREAD

**Issue by thmosqueiro** [bmcage/odes#11]
Hey, guys, really nice work!

I checked in cvode.pyx and apparently CVODE's default multistep (lmm_type in defaults dictionary) method is BDF, is that right? Just wanted a confirmation. Maybe I didn't see it, but I couldn't find it on the documentation.

**Comment by bmcage** [comment]
Yes. See the doc field of set_options of cvode, file cvode.pyx:
            'lmm_type'  - linear multistep method
                Values: 'ADAMS', 'BDF' (= default)
                Description:
                    Recommended combination:

                    Problem  | 'lmm_type' | 'iter_type'
                    ------------------------------------
                    nonstiff | 'ADAMS'    | 'FUNCTIONAL'
                    stiff    | 'BDF'      | 'NEWTON'

                    See also 'iter_type'.
            'iter_type' - nonlinear solver iteration
                Values: 'NEWTON' (= default), 'FUNCTIONAL'
                Description:
                    See 'lmm_type'.
