### ISSUE TITLE
Re-importing scikits.odes seems to break it

### ISSUE THREAD

**Issue by ma-sadeghi** [bmcage/odes#128]
I use Spyder IDE with its embedded IPython console to write/run Python code. If you run the code snippet in #127 more than once (in the same IPython console), the package seems to break and no longer returns correct values (actually, most of the time it diverges, it only runs correctly the first time). So, every time I have to restart Spyder's IPython console for it to work. I don't exactly know what's causing the issue, but it seems to occur when re-importing the already imported `scikits.odes` library.

**Comment by bmcage** [comment]
could this be the fact no init of the solution happened in #127 like in #129, and memory at start is 0, but over time memory used on np.empty(...) calls actually contain more and more contaminated values ?

**Comment by ma-sadeghi** [comment]
Yes! That was the issue! Setting du to 0 seems to have fixed the issue.
