### ISSUE TITLE
Unable to "conda install -c conda-forge scikits.odes" in  osx-arm64

### ISSUE THREAD

**Issue by SiddhaSharma** [bmcage/odes#140]
Unable to install scikits.odes
ERROR::

> PackagesNotFoundError: The following packages are not available from current channels:
> 
>   - scikits.odes
> 
> Current channels:
> 
>   - https://repo.anaconda.com/pkgs/main/osx-arm64
>   - https://repo.anaconda.com/pkgs/main/noarch
>   - https://repo.anaconda.com/pkgs/r/osx-arm64
>   - https://repo.anaconda.com/pkgs/r/noarch
>   - https://conda.anaconda.org/conda-forge/osx-arm64
>   - https://conda.anaconda.org/conda-forge/noarch

**Comment by aragilar** [comment]
You'll need to file a issue with the conda-forge package maintainers, this isn't a scikits.odes issue.

**Comment by SiddhaSharma** [comment]
Thanks! Apologies.
