### ISSUE TITLE
Conda install for arm64? 

### ISSUE THREAD

**Issue by decaluwe** [bmcage/odes#148]
Hi, I just upgraded to a laptop with apple's m2 chip.  Conda install of scikits.odes via
`conda install -c conda-forge scikits.odes`
now fails with 
```
PackagesNotFoundError: The following packages are not available from current channels:

  - scikits.odes

Current channels:

  - https://conda.anaconda.org/conda-forge/osx-arm64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/osx-arm64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-arm64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```
I'm not 100% conversant in these things, but assume this has to do with scikits.odes not being available on arm-compatible channels.  Is that correct, and if so, is there a recommended way to install on M2 chips? Build from source, perhaps?

Thanks in advance for any help.

**Comment by aragilar** [comment]
You'd need to ask the conda-forge folks why there's no Apple ARM packages, as we don't maintain the conda-forge packages. I haven't done any testing on Apple's ARM chips, so if you do encounter any bugs, do let us know. I don't know of any reason scikits.odes wouldn't work though.

**Comment by RabiTahir** [comment]
The current OS version (Ventura 13.2.1) ships with Python 3.9. On M1 (arm64), scikits-odes build due to 
--arch conflicts when linking against sundials (clang is being called with both -arch arm64 and -arch x86_64, i.e., building for macOS-x86_64 but ld will be attempting to link with file built for macOS-arm64?):

To be more explicit, this command fails (apple shipped python 3.9):
/usr/bin/pip3 install --force-reinstall --no-deps --no-cache scikits-odes  

However, this command succeeds (home-brew with python 3.11):
/opt/homebrew/bin/pip3 install --force-reinstall --no-deps --no-cache scikits-odes

....

Successfully installed scikits-odes-2.7.0

**Comment by RabiTahir** [comment]
> Hi, I just upgraded to a laptop with apple's m2 chip. Conda install of scikits.odes via `conda install -c conda-forge scikits.odes` now fails with
> 
> ```
> PackagesNotFoundError: The following packages are not available from current channels:
> 
>   - scikits.odes
> 
> Current channels:
> 
>   - https://conda.anaconda.org/conda-forge/osx-arm64
>   - https://conda.anaconda.org/conda-forge/noarch
>   - https://repo.anaconda.com/pkgs/main/osx-arm64
>   - https://repo.anaconda.com/pkgs/main/noarch
>   - https://repo.anaconda.com/pkgs/r/osx-arm64
>   - https://repo.anaconda.com/pkgs/r/noarch
> 
> To search for alternate channels that may provide the conda package you're
> looking for, navigate to
> 
>     https://anaconda.org
> 
> and use the search bar at the top of the page.
> ```
> 
> I'm not 100% conversant in these things, but assume this has to do with scikits.odes not being available on arm-compatible channels. Is that correct, and if so, is there a recommended way to install on M2 chips? Build from source, perhaps?
> 
> Thanks in advance for any help.

Please see my comment below, hope it helps you build scikits.odes on your machine. I was able to do this on M1 (arm64) with the provided instructions.

**Comment by decaluwe** [comment]
Many thanks, @RabiTahir. I did try your solution and was still getting a build fail.  Perhaps due to sundials install compatibility? Idk.  I eventually went back and on a whim tried conda again and it worked. No idea why. 🤷 

Thank you both for your help, though.
