### ISSUE TITLE
Conda Installation - Lapack Error

### ISSUE THREAD

**Issue by testcan** [bmcage/odes#154]
Hello all,

I have installed the scikits.ode using the conda installation: conda install -c conda-forge scikits.odes.

The installation was successfull but when i try to use a different linear_solver from the dense one i got the Lapack error:

solution = ode('cvode', van_der_pol, lmm_type='bdf' ,linsolver='lapackdense',rtol=1e-6,atol=1e-12).solve(np.linspace(t0,500,200), y0)

ValueError: LinSolver: LAPACK not available, cannot execute solver type: lapackdense

I dont understand why, as the the lliblapack 3.9 is installed in the python enviroment. Am i doing something wrong in the installation?

Thanks in advance,

**Comment by aragilar** [comment]
That means that the SUNDIALS that scikits.odes was built against lacked LAPACK support (see https://github.com/bmcage/odes/blob/57466a97a278f687a6b0a92343b767c495834b31/setup_build.py#L104-L112). Why that's the case, I don't know, you'd need to ask the conda-forge maintainers, but it's not something you did wrong. I'm closing this as there's not much we can do on our end.
