### ISSUE TITLE
Installation error using Nix

### ISSUE THREAD

**Issue by joshiqc** [bmcage/odes#156]
I have never used Nix before and I'm getting the following error:

nix-shell -p python37Packages.scikits-odes -p python37Packages.numpy --run "python3"
error:
       … while calling the 'derivationStrict' builtin

         at /builtin/derivation.nix:9:12: (source not available)

       … while evaluating derivation 'shell'
         whose name attribute is located at /nix/store/gr56h3j50piy85qnhid3098szym5inp2-nixpkgs/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:300:7

       … while evaluating attribute 'buildInputs' of derivation 'shell'

         at /nix/store/gr56h3j50piy85qnhid3098szym5inp2-nixpkgs/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:347:7:

          346|       depsHostHost                = lib.elemAt (lib.elemAt dependencies 1) 0;
          347|       buildInputs                 = lib.elemAt (lib.elemAt dependencies 1) 1;
             |       ^
          348|       depsTargetTarget            = lib.elemAt (lib.elemAt dependencies 2) 0;

       error: undefined variable 'python37Packages'

       at «string»:1:107:

            1| {...}@args: with import <nixpkgs> args; (pkgs.runCommandCC or pkgs.runCommand) "shell" { buildInputs = [ (python37Packages.scikits-odes) (python37Packages.numpy) ]; } ""
             |                                                  

How do I fix this?

Sandeep

**Comment by aragilar** [comment]
I think you would need to ask on the various nix support forums, the nix support was done by nix users.
