### ISSUE TITLE
support for `sundials>=6.6`

### ISSUE THREAD

**Issue by Naikless** [bmcage/odes#161]
The current releases available via conda-forge only support `sundials` versions `<6.6.0`. 

Is there a chance to add a version that supports newer versions of sundials? 

The backgound is that I am trying to update some of the [jupyter examples of cantera](https://github.com/Cantera/cantera-jupyter) and some make use of `scikits.odes.dae`. Problem is that the newest cantera version only supports `sundials>6.6.0` which makes this dependency currently unsolvable.

**Comment by callegar** [comment]
This is also a problem with all the linux distros based on arch, that currently ships only sundials 7.

**Comment by callegar** [comment]
Incidentally, is sundials 6.7 supported? Apparently, `pip install scikits.odes` works fine against it, but from the current report I wonder if there is some issue to be expected later...
