### ISSUE TITLE
Splitting scikits.odes into multiple packages

### ISSUE THREAD

**Issue by aragilar** [bmcage/odes#166]
Currently we're stuck on Python 3.11 and earlier due to the distutils changes (see #130). In order to resolve this, and because a simple port to meson isn't possible, I'm suggesting splitting this into multiple packages (but which will still be in the same repository for now).

Currently scikits.odes is composed of four parts:
* bindings to `daepack` via `f2py`
* bindings to `sundials` via `cython`
* bindings to the various scipy integrators (via imports)
* a standard interface to the above

meson and sundials/cython don't really align, and f2py is now tied to meson. It would seem the best way would be a split into three packages:
* `scikits-odes-daepack` which uses meson and f2py to provide the required wrappers around daepack
* `scikits-odes-sundials` which uses setuptools and cython to wrap sundials
* `scikits.odes` which provides the standard interface, and imports the above 2 packages (plus scipy) to keep a mostly backwards-compatible interface to the current package (some imports would break, but we can try to provide some compat imports where possible.

@bmcage Do you have any suggestions/ideas/opinions on this?

**Comment by aragilar** [comment]
I've got a first pass at making `scikits-odes-daepack` work going, I think it would make sense to create `scikits-odes-core` with the base cases, and just have the autodetection of backends in `scikits.odes` (as it makes it easier to test the bindings).

**Comment by bmcage** [comment]
Looks good to me. Packaging is not my expertise unfortunately.

**Comment by aragilar** [comment]
I've merged this in #168.
