### ISSUE TITLE
is it possible to get the result of CVodeGetNumRhsEvals with python code?

### ISSUE THREAD

**Issue by logicabrity** [bmcage/odes#28]
I'm trying to find out how many evaluations of the RHS the integrator needed to reach a certain time. Is it possible to get the result of CVodeGetNumRhsEvals? Haven't found anything besides the definition while digging through the code base.

If I haven't overlooked it, I'd be happy to implement this. Any preferences for the API? I'm imagining adding it to the CVODE class in `scikits/odes/sundials/cvode.pyx`.

**Comment by bmcage** [comment]
This function is indeed not exposed to python. 
i cannot test at the moment, in cython code you probably can use it by leveraging CVODE._cv_mem

Better indeed to implement it in the API. Haven't thought of an API. There are many numevals methods, some way that can be easily extended would be best. Perhaps an info dict return on ode.get_info().
I don't like the full_output flag of odeint (http://docs.scipy.org/doc/scipy-0.17.0/reference/generated/scipy.integrate.odeint.html), see infodict object in return. 
So in odes/ode.py to add a get_info method that returns a dict. Only returns a non-empty dict if the integrator has a get_info method.
Then in cvode.pyx a get_info method in class CVODE, that fills up the dict. So eg
{'NumRhsEvals' : 3 }
if you only expose CVodeGetNumRhsEvals.
