### ISSUE TITLE
Specifying the compiler for ODES build on Mac OS X

### ISSUE THREAD

**Issue by OrbitalMechanic** [bmcage/odes#31]
I'm attempting to build ODES on a MacBook Pro running Mac OS X El Capitan (10.11.6). The problem I'm having is with the build ODES Scikits step of the procedure (see attached file).

One issue I've observed is that the script uses the gfortran compiler instead of the Absoft 2016 Pro Fortran compiler used in building the sundials procedure.

Please advise.
[build_log_odes.txt](https://github.com/bmcage/odes/files/441497/build_log_odes.txt)

**Comment by aragilar** [comment]
So the Fortran part should be irrelevant as neither sundials nor the cython code linking to sundials uses Fortran (sundials creates Fortran binding, but the main code is in C, scikits.odes has other solvers besides sundials which are written in Fortran).
Googling "CYTHON_INLINE on osx 'inline' can only appear on functions" shows that this is related to cython, not scikits.odes. It also suggests this is due to which compiler is being used. Can you work out which compiler is being used (name, version, who provides it (system, conda, other package manager you're using etc.))?

**Comment by rubendibattista** [comment]
In addition all the entries that could be found on Google are related to Anaconda. 
I suggest you to install the Python Stack with something like Macports or Brew. That way should be even easier to understand which compiler you are using (and setting it too...).

**Comment by OrbitalMechanic** [comment]
Thank you responding so quickly.

The compiler versions I'm using are:
gcc: Apple LLVM version 7.3.0 (clang-703.0.31)
gfortran: GNU Fortran (GCC) 6.1.0 from http://hpc.sourceforge.net/
cython: Cython version 0.24.1 from conda

Hope this helps.

Sam Dupree.

**Comment by aragilar** [comment]
So your gcc isn't gcc, which probably doesn't help cython. I'd suggest installing a real gcc (via conda, or however else you want to do it), as it sounded like clang has issues with cython. Besides that, this really is a cython issue, so you're going to need to ask them for a fix.

I'd also suggest you use one system to manage your code, whether it's conda, macports, fink or homebrew, as especially with OSX and the clang/gcc thing, there can be weird things happening.

**Comment by bmcage** [comment]
clang treats inline different from gcc, so you obtain errors. 

Remove "inline" for all four datatype-translating functions in common_defs.pxd manually, and try compile again, it should work. 

Not sure if compile will finish then though, as previous person I tried to help with this error had fortron compile issues after this. So let me know if you maanage.

Not sure how to fix generally. Removing inline obviously means gcc will not treat the functions as inline anymore with a possible slowdown in execution ?

**Comment by utsekaj42** [comment]
I have been able to solve this issue for myself. I can submit a patch detailing the installation options for macOS (within a conda environment). I'm fairly sure the same approach would also work for macOS if you have installed gcc and gfortran in some other manner. I have not tested this however.

There are 2 ways I have managed to install sundials for this purpose.
The simplest is to install the conda-forge package
`conda install -c conda-forge sundials==2.7.0`

Alternatively you can build it into the conda environment's `~/anaconda/envs/env_name/lib` and `~/anaconda/envs/env_name/include` directories by changing the cmake command to
`cmake -DLAPACK_ENABLE=ON -DCMAKE_INSTALL_PREFIX=~/anaconda/envs/env_name ../sundials-2.7.0`

If your conda environment doesn't already have `gcc` installed install it by
`conda install gcc`

Now you should be able to install the package from pypi directly as
`CC=gcc pip install scikits.odes`

Alternatively to install with `setup.py` first  add `os.environ["CC"]="gcc"` to `setup.py` after importing `os`.  
Now the following should install successfully
```
python setup.py build
python setup.py install
```
and you should be able to `cd` to a different directory and run the tests
```
python "import scikits.odes as od; od.test()
```
Again this assumes you have installed all the other dependencies in your conda environment.

**Comment by bmcage** [comment]
Closing as we don't plan code changes at the moment for this, and solution is in this thread.
