### ISSUE TITLE
Documentation for cvode interface is sparse.

### ISSUE THREAD

**Issue by tsbertalan** [bmcage/odes#38]
I'm working from the the `freefall.py` example.  I see how to find roots, and, I infer that the `nr_rootfns=1` keyword argument is used to save them in the object returned when `old_api=False` is given (though I can't find any documentation of this).

Is there any better documentation for the keyword arguments available when using cvode? I see

    options :  additional options of the solver
        See set_options method of the `integrator_name` you selected for
        details.
        Set option `old_api=False` to use the new API. In the future, this
        will become the default!

In the docstring for `scikits.odes.ode`, but the docstring for my cvode solver's `set_options` method is just

    Set specific options for the solver.
    See the solver documentation for details.

    Calling set_options a second time, is only possible for options that
    can change during runtime.

This is true whether or not I create the solver with `old_api=False`.

**Comment by bmcage** [comment]
This module is mainly a wrapper around cvode, so the doc of cvode applies:
http://computation.llnl.gov/projects/sundials/usage-notes
See pdf guide on this page: http://computation.llnl.gov/projects/sundials/sundials-software 

So options exposed in the wrapper are mostly  1-1 with the options of the C code. What they do and how they affect the solver is detailed in the docs of cvode.

**Comment by bmcage** [comment]
For the options, see the set_options func, the doc string should be as in the code:
https://github.com/bmcage/odes/blob/master/scikits/odes/sundials/cvode.pyx#L643

**Comment by bmcage** [comment]
There is now new doc: http://scikits-odes.readthedocs.io/en/latest/
and also api doc: https://bmcage.github.io/odes/
