### ISSUE TITLE
IDA option algebraic_vars_idx documentation is wrong

### ISSUE THREAD

**Issue by paulhprobert** [bmcage/odes#41]
in the file ida.pyx there is a description of the option 'algebraic_vars_idx' that says "... These are denoted by the position (index) in the residual vector..."  This is wrong.  It should be "... These are denoted by the position (index) in the state vector y..."

This may seem like a small thing, but it caused me some grief.  This change also aligns the documentation with the way Octave documents its implementation of IDA.

Thanks!

**Comment by bmcage** [comment]
Yes, this is the IDASetId function in the IDA doc, http://computation.llnl.gov/sites/default/files/public/ida_guide.pdf

fixed in commit 570caa44eb1f388cab07505f83c55d206ae88279
