### ISSUE TITLE
Make scikits.odes citable

### ISSUE THREAD

**Issue by aragilar** [bmcage/odes#42]
One of my officemates was trying to cite scikits.odes (in https://arxiv.org/abs/1612.09383), but there's currently no citable object (e.g. paper, doi). We should add to http://joss.theoj.org/ (and maybe http://ascl.net/), so that scikits.odes can be cited.

**Comment by bmcage** [comment]
I set up a paper.md and paper.bib: https://github.com/bmcage/odes/tree/master/paper 
Feel free to improve on it via a PR.
I did a submission to joss, see http://joss.theoj.org/papers/59d3b2e50db759e4255736236e13193d 
Let's see what comes of it.

**Comment by bmcage** [comment]
Although JOSS submission is not over yet, via zenodo there is now a DOI: https://zenodo.org/record/292988#.WKb72mcjxFQ
