### ISSUE TITLE
The release version for JOSS needs a DOI

### ISSUE THREAD

**Issue by arghdos** [bmcage/odes#47]
See this [github page](https://guides.github.com/activities/citable-code/) for a good guide to get a DOI via Zenodo.  The badge can also be added to the read-me if desired

**Comment by bmcage** [comment]
Zenodo release done, as this is different from before, the Zenodo release with DOI is v2.3.1
Procedures changed for the future so all releases will be now via github release and Zenodo
commit 279a8f0424d9d12f6f6f72506415892451729322
