### ISSUE TITLE
Can't install with pip (in conda)

### ISSUE THREAD

**Issue by dcasasor** [bmcage/odes#56]
I've been struggling with the instalation of scikits.odes through pip. I am currently working with Anaconda so I installed sundials using `conda install -c conda-forge sundials`. Then, I read the conda documentation and said that for non-conda packages (like scikits.odes), one can use pip.

So I did sudo `pip install scikits.odes` and surprisingly, an error occurred while executing setup.py, specifically: `ImportError: No module named 'numpy'`.

I don't know why numpy is not found during the installation. Any ideas on how to fix this problem?

Python version: 2.7
conda version: 4.3.29
pip version: 9.0.1
scikits.odes version: 2.3.1
OS: Linux Mint 18

Thanks.

**Comment by dcasasor** [comment]
Hi. I finally managed to install scikits.odes through pip. I had to do `source activate` before using pip.

However, I still have problems with the installation. When I try to run a script using the cvode integrator, scikits.odes says: `ValueError: Integrator name cvode does not exist`. I suspected that the reason was I did not set the SUNDIALS_INST environment variable to the anaconda installation path. So I uninstalled scikits.odes and then set this variable doing:

`SUNDIALS_INST=${HOME}/anaconda2/pkgs/sundials-3.1.0-blas_openblas_200`
`export SUNDIALS_INST`

Then, I installed scikits.odes again:

`source activate`
`pip install scikits.odes`

Althoug the installation is succesfull, the problem persists (cvode is not found). I honestly don't know what else I can do to get scikits.odes to work again.

**Comment by aragilar** [comment]
First, don't sudo pip firstly, sudo pip is (almost) never the right answer.

Can you check the following things:
 * The path to pip (are you using the correct pip)
 * The path to python (are you using the correct python)
 * The contents of `$LD_LIBRARY_PATH`

**Comment by dcasasor** [comment]
Hi aragilar. Thanks for your response.

This is what i found:
`which pip`: `/home/casasorozco/anaconda2/bin/pip`
`which python`:  `/home/casasorozco/anaconda2/bin/python`
`echo LD_LIBRARY_PATH`: nothing appears

Is this what I was supposed to verify? Thanks again.

**Comment by aragilar** [comment]
Did you do `echo LD_LIBRARY_PATH` or `echo $LD_LIBRARY_PATH`, those are two different things.

If you create a new conda environment, and install into that environment using conda sundials, numpy and cython, `pip install scikits.odes` should work. If it doesn't, can you post the entire output from pip.

**Comment by dcasasor** [comment]
Hi aragilar. I did `echo $LD_LIBRARY_PATH` (sorry for the typo). The result was a blank line.

On the other hand, I tried creating a new environment with numpy and cython:

`conda create -n odes numpy cython`

and then added sundials from the *conda-forge* channel:

`conda install -n odes -c conda-forge sundials=2.7.0`

Then, I activated the *odes* environment:

`source activate odes`

and installed scikits.odes with pip:

`pip install scikits.odes`

However, the problem appears again when running the script:

  File "/home/casasorozco/anaconda2/envs/odes/lib/python2.7/site-packages/scikits/odes/ode.py", line 469, in find_ode_integrator
    raise ValueError('Integrator name %s does not exist' % name)
ValueError: Integrator name cvode does not exist

**Comment by aragilar** [comment]
Ok, can you uninstall scikits.odes, and then use `pip install -v scikits.odes` and post the output?

**Comment by dcasasor** [comment]
This is the complete output after the installation inside the *odes* environment:

Collecting scikits.odes
  1 location(s) to search for versions of scikits.odes:
  * https://pypi.python.org/simple/scikits-odes/
  Getting page https://pypi.python.org/simple/scikits-odes/
  Looking up "https://pypi.python.org/simple/scikits-odes/" in the cache
  Current age based on date: 55
  Freshness lifetime from max-age: 600
  Freshness lifetime from request max-age: 600
  The response is "fresh", returning cached response
  600 > 55
  Analyzing links from page https://pypi.python.org/simple/scikits-odes/
    Found link https://pypi.python.org/packages/03/f5/d539462038c87d0c5236425af9cc76a7479c6acbb95bd020331601a9de12/scikits.odes-2.2.1.tar.gz#md5=98e1b70adc70c1144f4f86200a66da18 (from https://pypi.python.org/simple/scikits-odes/), version: 2.2.1
    Found link https://pypi.python.org/packages/2a/86/784143925f519e77d85d845f890a0a280deee96ed70f41148ec7337ea931/scikits.odes-2.2.0.tar.gz#md5=50757ad69acffc780eb87e162c4b4ae6 (from https://pypi.python.org/simple/scikits-odes/), version: 2.2.0
    Found link https://pypi.python.org/packages/2d/f0/271b1934f7a9e9f7351620abc60d7324f191e1c058258a69255f8426863c/scikits.odes-1.0.0.zip#md5=cfdf7c3a982f24845bad85136c240257 (from https://pypi.python.org/simple/scikits-odes/), version: 1.0.0
    Found link https://pypi.python.org/packages/40/b8/5efbce2bdb177f68a59178f34d04f90599541713543d1735516172aa2aa2/scikits.odes-1.0.0dev.tar.gz#md5=622ffee3ab072697cc4760c9da6c5b1d (from https://pypi.python.org/simple/scikits-odes/), version: 1.0.0dev
    Found link https://pypi.python.org/packages/60/0f/b8bcdb45bf37d09b3b162500f44b1743e23e7b80753a3c170adacdccec88/scikits.odes-2.2.1.zip#md5=39a08d4e63aa5ae1b84692d400e154f1 (from https://pypi.python.org/simple/scikits-odes/), version: 2.2.1
    Found link https://pypi.python.org/packages/7f/eb/2dc3a695177712e495ade4b7b3e5a6a91c2e2a6bac0caf5765b7b825901b/scikits.odes-2.3.1.tar.gz#md5=a667e551c58d4e8ac4f952746ffcde43 (from https://pypi.python.org/simple/scikits-odes/), version: 2.3.1
    Found link https://pypi.python.org/packages/9c/f8/a8e7fd333c223184ead6983c85fc74c7c5437a482c418963113d639dad39/scikits.odes-2.2.0.zip#md5=3579a82f7c215ce3ffcef99fcb3bb4a4 (from https://pypi.python.org/simple/scikits-odes/), version: 2.2.0
    Found link https://pypi.python.org/packages/af/03/bc858909a207c86dded00f80c54f3fedcc7d5301cdbef494a4eb8ac395c9/scikits.odes-1.0.0.tar.gz#md5=3a912ccffd3f9e34bd9b0abe1c7361ee (from https://pypi.python.org/simple/scikits-odes/), version: 1.0.0
    Found link https://pypi.python.org/packages/b3/50/76141dafa077c0aa58a908d497c7a6d48fef70f1ee58356299bd46d98e8b/scikits.odes-2.0.2.tar.gz#md5=aa75bd8575731c5b051fe85160103f0f (from https://pypi.python.org/simple/scikits-odes/), version: 2.0.2
    Found link https://pypi.python.org/packages/b4/de/8908b0f4073e7968dba5f91149efc3f25391c959156e7a5f955e742d14ed/scikits.odes-2.1.0.zip#md5=82e8cbb40cd919c228df23890406bf22 (from https://pypi.python.org/simple/scikits-odes/), version: 2.1.0
    Found link https://pypi.python.org/packages/e3/5c/caabe2c85e6f5aa44b2688ef0c2f5ee77ad6737579e3b52ac616a2d55a66/scikits.odes-2.0.2.zip#md5=ff8dba88ce522bad8144c1f2f06f0713 (from https://pypi.python.org/simple/scikits-odes/), version: 2.0.2
    Found link https://pypi.python.org/packages/fe/ea/f7db9b802a8d4d1665d60784e15424508e8303739970f7213300d974a18b/scikits.odes-2.1.0.tar.gz#md5=eb1f89a832a7de439c74fa8e3ec7934b (from https://pypi.python.org/simple/scikits-odes/), version: 2.1.0
  Using version 2.3.1 (newest of versions: 1.0.0, 2.0.2, 2.1.0, 2.2.0, 2.2.1, 2.3.1)
  Using cached wheel link: file:///home/casasorozco/.cache/pip/wheels/50/fa/c4/ade061d8db9c821f895586c3113ec30b279ab64b0e0a08c88b/scikits.odes-2.3.1-cp27-cp27mu-linux_x86_64.whl
Requirement already satisfied: scipy in ./anaconda2/envs/odes/lib/python2.7/site-packages (from scikits.odes)
Requirement already satisfied: enum34 in ./anaconda2/envs/odes/lib/python2.7/site-packages (from scikits.odes)
Requirement already satisfied: numpy>=1.8.2 in ./anaconda2/envs/odes/lib/python2.7/site-packages (from scipy->scikits.odes)
Installing collected packages: scikits.odes

Successfully installed scikits.odes-2.3.1
Cleaning up...

**Comment by dcasasor** [comment]
This is the complete output after installing inside the *odes* environment:

Collecting scikits.odes
  1 location(s) to search for versions of scikits.odes:
  * https://pypi.python.org/simple/scikits-odes/
  Getting page https://pypi.python.org/simple/scikits-odes/
  Looking up "https://pypi.python.org/simple/scikits-odes/" in the cache
  Current age based on date: 55
  Freshness lifetime from max-age: 600
  Freshness lifetime from request max-age: 600
  The response is "fresh", returning cached response
  600 > 55
  Analyzing links from page https://pypi.python.org/simple/scikits-odes/
    Found link https://pypi.python.org/packages/03/f5/d539462038c87d0c5236425af9cc76a7479c6acbb95bd020331601a9de12/scikits.odes-2.2.1.tar.gz#md5=98e1b70adc70c1144f4f86200a66da18 (from https://pypi.python.org/simple/scikits-odes/), version: 2.2.1
    Found link https://pypi.python.org/packages/2a/86/784143925f519e77d85d845f890a0a280deee96ed70f41148ec7337ea931/scikits.odes-2.2.0.tar.gz#md5=50757ad69acffc780eb87e162c4b4ae6 (from https://pypi.python.org/simple/scikits-odes/), version: 2.2.0
    Found link https://pypi.python.org/packages/2d/f0/271b1934f7a9e9f7351620abc60d7324f191e1c058258a69255f8426863c/scikits.odes-1.0.0.zip#md5=cfdf7c3a982f24845bad85136c240257 (from https://pypi.python.org/simple/scikits-odes/), version: 1.0.0
    Found link https://pypi.python.org/packages/40/b8/5efbce2bdb177f68a59178f34d04f90599541713543d1735516172aa2aa2/scikits.odes-1.0.0dev.tar.gz#md5=622ffee3ab072697cc4760c9da6c5b1d (from https://pypi.python.org/simple/scikits-odes/), version: 1.0.0dev
    Found link https://pypi.python.org/packages/60/0f/b8bcdb45bf37d09b3b162500f44b1743e23e7b80753a3c170adacdccec88/scikits.odes-2.2.1.zip#md5=39a08d4e63aa5ae1b84692d400e154f1 (from https://pypi.python.org/simple/scikits-odes/), version: 2.2.1
    Found link https://pypi.python.org/packages/7f/eb/2dc3a695177712e495ade4b7b3e5a6a91c2e2a6bac0caf5765b7b825901b/scikits.odes-2.3.1.tar.gz#md5=a667e551c58d4e8ac4f952746ffcde43 (from https://pypi.python.org/simple/scikits-odes/), version: 2.3.1
    Found link https://pypi.python.org/packages/9c/f8/a8e7fd333c223184ead6983c85fc74c7c5437a482c418963113d639dad39/scikits.odes-2.2.0.zip#md5=3579a82f7c215ce3ffcef99fcb3bb4a4 (from https://pypi.python.org/simple/scikits-odes/), version: 2.2.0
    Found link https://pypi.python.org/packages/af/03/bc858909a207c86dded00f80c54f3fedcc7d5301cdbef494a4eb8ac395c9/scikits.odes-1.0.0.tar.gz#md5=3a912ccffd3f9e34bd9b0abe1c7361ee (from https://pypi.python.org/simple/scikits-odes/), version: 1.0.0
    Found link https://pypi.python.org/packages/b3/50/76141dafa077c0aa58a908d497c7a6d48fef70f1ee58356299bd46d98e8b/scikits.odes-2.0.2.tar.gz#md5=aa75bd8575731c5b051fe85160103f0f (from https://pypi.python.org/simple/scikits-odes/), version: 2.0.2
    Found link https://pypi.python.org/packages/b4/de/8908b0f4073e7968dba5f91149efc3f25391c959156e7a5f955e742d14ed/scikits.odes-2.1.0.zip#md5=82e8cbb40cd919c228df23890406bf22 (from https://pypi.python.org/simple/scikits-odes/), version: 2.1.0
    Found link https://pypi.python.org/packages/e3/5c/caabe2c85e6f5aa44b2688ef0c2f5ee77ad6737579e3b52ac616a2d55a66/scikits.odes-2.0.2.zip#md5=ff8dba88ce522bad8144c1f2f06f0713 (from https://pypi.python.org/simple/scikits-odes/), version: 2.0.2
    Found link https://pypi.python.org/packages/fe/ea/f7db9b802a8d4d1665d60784e15424508e8303739970f7213300d974a18b/scikits.odes-2.1.0.tar.gz#md5=eb1f89a832a7de439c74fa8e3ec7934b (from https://pypi.python.org/simple/scikits-odes/), version: 2.1.0
  Using version 2.3.1 (newest of versions: 1.0.0, 2.0.2, 2.1.0, 2.2.0, 2.2.1, 2.3.1)
  Using cached wheel link: file:///home/casasorozco/.cache/pip/wheels/50/fa/c4/ade061d8db9c821f895586c3113ec30b279ab64b0e0a08c88b/scikits.odes-2.3.1-cp27-cp27mu-linux_x86_64.whl
Requirement already satisfied: scipy in ./anaconda2/envs/odes/lib/python2.7/site-packages (from scikits.odes)
Requirement already satisfied: enum34 in ./anaconda2/envs/odes/lib/python2.7/site-packages (from scikits.odes)
Requirement already satisfied: numpy>=1.8.2 in ./anaconda2/envs/odes/lib/python2.7/site-packages (from scipy->scikits.odes)
Installing collected packages: scikits.odes

Successfully installed scikits.odes-2.3.1
Cleaning up...

**Comment by aragilar** [comment]
Ok, you're using a cached wheel. Go to ~/.cache/pip/wheels, and delete the contents of that directory, and reinstall scikits.odes.

**Comment by dcasasor** [comment]
Thanks a lot. Your suggestion solved my problem. Have a nice day :D
