### ISSUE TITLE
move to sundials 3.1.1

### ISSUE THREAD

**Issue by bmcage** [bmcage/odes#76]
We should move to latest sundials. 
Much to do as solvers have been abstracted away. 

start of a working branch: https://github.com/bmcage/odes/tree/sundials_3_1

**Comment by bmcage** [comment]
Apart from other changes, also SUNDIALS_INDEX_TYPE must be set to int32_t from the default int64_t to be able to use LAPACK. Should become a usersettable option if we can make odes work without LAPACK.
-DSUNDIALS_INDEX_TYPE=int32_t

**Comment by aragilar** [comment]
There's now a 3.1.1 release (with a 4.0 release planned later this year). I plan on looking at this in the next few weeks.

**Comment by bmcage** [comment]
Great, I try to make time in my schedule also, but many deadlines in work projects make that hard. I was hoping for small changes as needed for previous updates, but no deal, the changes are extensive. We will however be able to do away with hard dependency on LAPACK if we do it right!
