### ISSUE TITLE
pip install fails on my Arch box

### ISSUE THREAD

**Issue by paulhprobert** [bmcage/odes#84]
Been using odes for a year or so but suddenly won't work. I'm on python 3.7.0, Arch linux. Sundials 3.1.2 is installed. I try reinstalling with pip install scikits.odes and get many errors as below.  Thanks for any help!
[odes_errors.txt](https://github.com/bmcage/odes/files/2279803/odes_errors.txt)

**Comment by paulhprobert** [comment]
Hey, that worked!  Thanks!

**Comment by bmcage** [comment]
Mergedin master now. 
I'll wait a bit before a release to see if no issues pop up. Probably some doc changes to do also still.
