### ISSUE TITLE
define another parameter in eqsrhs when using CVODE?

### ISSUE THREAD

**Issue by artgoldberg** [bmcage/odes#85]
Hello Folks

Is it possible to pass a python reference to scikits.odes.ode.ode() and then have the solver pass the reference back to eqsrhs()? It appears from

                    Values: function of class CV_RhsFunction or a python function
                        with signature (t, y, yp) or (t, y, yp, userdata)

in odes/scikits/odes/sundials/cvode.pyx that this might be possible, but I'm not confident that I understand it.

The reference would be handy, but not essential. Otherwise I can hack a class variable that eqsrhs() can use to obtain the necessary data.

Thanks
Arthur

**Comment by bmcage** [comment]
Yes, this is not planned. For normal use, create an object and use self, as in 

https://github.com/bmcage/odes/blob/master/ipython_examples/Double%20Pendulum%20as%20DAE%20with%20roots.ipynb

For simple tests, consider just a global class or globa data.
For advanced use and doing as much speedup as possibile, consider cython and inherit CV_RhsFunction which has user_data (but overkill for 99% of situations)

    from scikits.odes.sundials.cvode cimport CV_RhsFunction

https://github.com/bmcage/odes/blob/master/ipython_examples/Cython%20cvode%20speedup.ipynb

**Comment by bmcage** [comment]
Thinking some more about this, I never tried CV_RhsFunction with userdata, but I believe theoretically it must be possible. Example always welcome!

**Comment by artgoldberg** [comment]
Thanks Benny. For now I'm using a class global as you also suggested.

When I have time I'll try userdata and let you know what happens with examples.

Arthur
