### ISSUE TITLE
Make Install Process Easier

### ISSUE THREAD

**Issue by idontgetoutmuch** [bmcage/odes#96]
I spent several hours installing this morning :( I'm still not convinced everything is correct #95 but I can solve a simple ode now).

Even installing sundials wasn't entirely trivial. It would better to use homebrew or nixpkgs to ensure the required version (in fact nix or something similar is really the way to go packages that rely on other packages outside the the python ecosystem IMHO).

```
cd MyWorkingSundials/
cmake -DCMAKE_INSTALL_PREFIX=/Users/myname/MySundials/instdir -DEXAMPLES_INSTALL_PATH=/Users/myname/MySundials/instdir/examples /Users/myname/sundials-3.1.1
```

```
export SUNDIALS_INST=/Users/myname/MySundials/instdir
```

```
CC=gcc-9 pip3 install scikits.odes
```

```
export DYLD_LIBRARY_PATH=/Users/myname/MySundials/instdir/lib
```

I may have missed some steps.

**Comment by idontgetoutmuch** [comment]
I am just going to note that I have scikits-odes building under nix with lapack so all you have to do is

```
nix-shell -I nixpkgs=/Users/dom/nixpkgs -p python37Packages.scikits-odes  -p python37Packages.nose --run "python3"
```

And your python shell now has `scikits-odes` available - no installing sundials etc as it's all done for you by nix.

Actually you will be able to say

```
nix-shell -p python37Packages.scikits-odes  -p python37Packages.nose --run "python3"
```

as I was using a local copy of nixpkgs for testing.

**Comment by bmcage** [comment]
Can you do a PR request adding a section nix to the install documentation part? I have no experience with nix myself.

**Comment by idontgetoutmuch** [comment]
Sure :) I was going to suggest I sent you a PR but hadn't quite round to it. I'll wait until the PR to nixpkgs has been accepted though otherwise the instructions won't work leading to frustration.

**Comment by idontgetoutmuch** [comment]
I've added a placeholder PR: https://github.com/bmcage/odes/pull/102. Packaging scikits-odes and sundials for nix has been a voyage of experience (for far more details than you'd ever want, look here: https://github.com/NixOS/nixpkgs/pull/64195).
